//
//  FactBook.swift
//  FunFacts
//
//  Created by Ty Schenk on 5/27/15.
//  Copyright (c) 2015 Ty Schenk. All rights reserved.
//

import GameKit

struct FactModel {
    
    let facts = [
        "Ants stretch when they wake up in the morning.",
        "Ostritches can run faster than horses.",
        "Olympic gold medals are actually mostly made of silver.",
        "You are born with 300 bones; by the time you are an adult you will have 206.",
        "It takes about 8 minutes for light from the Sun to reach the Earth.",
        "Some bamboo plants can grow almost a meter in just one day.",
        "Some penguins can leap 2-3 meters out of the water.",
        "The state of Florida is bigger than England.",
        "On average, it takes 66 days to form a new habit.",
        "Mammoths still walked the Earth when the Great Pyramid was being built.",
        "Banging your head against a wall burns 150 calories an hour.",
        "In the UK, it is illegal to eat mince pies on Christmas Day!",
        "Pteronophobia is the fear of being tickled by feathers!",
        "When hippos are upset, their sweat turns red.",
        "A flock of crows is known as a murder.",
        "“Facebook Addiction Disorder” is a mental disorder identified by Psychologists.",
        "The average woman uses her height in lipstick every 5 years.",
        "29th May is officially “Put a Pillow on Your Fridge Day“.",
        "Cherophobia is the fear of fun.",
        "Human saliva has a boiling point three times that of regular water.",
        "If you lift a kangaroo’s tail off the ground it can’t hop.",
        "Hyphephilia are people who get aroused by touching fabrics.",
        "Billy goats urinate on their own heads to smell more attractive to females.",
        "The person who invented the Frisbee was cremated and made into frisbees after he died!",
        "During your lifetime, you will produce enough saliva to fill two swimming pools.",
        "An eagle can kill a young deer and fly away with it.",
        "Polar bears can eat as many as 86 penguins in a single sitting.",
        "King Henry VIII slept with a gigantic axe beside him.",
        "Bikinis and tampons invented were by men.",
        "If Pinokio says “My Noes Will Grow Now”, it would cause a paradox",
        "Heart attacks are more likely to happen on a Monday.",
        "If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!",
        "An average person’s yearly fast food intake will contain 12 pubic hairs.",
        "The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
        "There is a species of spider called the Hobo Spider.",
        "Penis Fencing’ is a scientific term for the mating ritual between flatworms. It involves two flatworms attempting to stab the other flatworm with their penis.",
        "A toaster uses almost half as much energy as a full-sized oven.",
        "A baby spider is called a spiderling.",
        "You cannot snore and dream at the same time.",
        "The following can be read forward and backwards: Do geese see God?",
        "A baby octopus is about the size of a flea when it is born.",
        "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
        "In Uganda, 50% of the population is under 15 years of age.",
        "Hitler’s mother considered abortion but the doctor persuaded her to keep the baby.",
        "Arab women can initiate a divorce if their husbands don’t pour coffee for them.",
        "Recycling one glass jar saves enough energy to watch TV for 3 hours.",
        "Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.",
        "Catfish are the only animals that naturally have an odd number of whiskers.",
        "Facebook, Skype and Twitter are all banned in China.",
        "95% of people text things they could never say in person.",
        "The Titanic was the first ship to use the SOS signal.",
        "In Poole, ‘Pound World’ went out of business because of a store across the road called ’99p Stores’, which was selling the same products but for just 1 pence cheaper!",
        "About 8,000 Americans are injured by musical instruments each year.",
        "The French language has seventeen different words for ‘surrender’.",
        "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
        "Bob Dylan’s real name is Robert Zimmerman.",
        "A crocodile can’t poke its tongue out :p",
        "Sea otters hold hands when they sleep so they don’t drift away from each other.",
        "A small child could swim through the veins of a blue whale.",
        "Bin Laden’s death was announced on 1st May 2011. Hitler’s death was announced on 1st May 1945.",
        "J.K. Rowling chose the unusual name ‘Hermione’ so young girls wouldn’t be teased for being nerdy!",
        "Hewlett-Packard’s name was decided in a coin toss.",
        "The total number of steps in the Eiffel Tower are 1665.",
        "The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Jackie Chan.",
        "The toothpaste ‘Colgate’ in Spanish translates to ‘go hang yourself’.",
        "Pirates wore earrings because they believed it improved their eyesight.",
        "Los Angeles’s full name is “El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula.”",
        "The testicles on an octopus are located in its head!",
        "In England, in the 1880’s, “Pants” was considered a dirty word.",
        "It snowed in the Sahara desert for 30 minutes on the 18th February 1979.",
        "Every human spent about half an hour as a single cell.",
        "If you leave everything to the last minute… it will only take a minute.",
        "Ithyphallophobia is the fear of erections.",
        "The first alarm clock could only ring at 4am.",
        "Birds don’t urinate.",
        "Dying is illegal in the Houses of Parliaments – This has been voted as the most ridiculous law by the British citizens.",
        "The word ‘ejaculation’ comes from the Latin word meaning ‘throwing out’.",
        "The 20th of March is known as Snowman Burning Day!",
        "Slugs have 4 noses.",
        "Panphobia is the fear of everything… which is a pretty unlucky phobia to have.",
        "An apple, potato, and onion all taste the same if you eat them with your nose plugged.",
        "George Washington grew marijuana in his garden.",
        "A company in Taiwan makes dinnerware out of wheat, so you can eat your plate!",
        "The average person walks the equivalent of twice around the world in a lifetime.",
        "The Bible is the most shoplifted book in the world.",
        "Marco Hort has the world record for fitting 264 straws in his mouth at once!",
        "Mel Blanc – the voice of Bugs Bunny – was allergic to carrots.",
        "California has issued 6 drivers licenses to people named Jesus Christ.",
        "According to Genesis 1:20-22 the chicken came before the egg.",
        "In the Caribbean there are oysters that can climb trees.",
        "Worms eat their own poo.",
        "Squirrels forget where they hide about half of their nuts.",
        "Over 1000 birds a year die from smashing into windows.",
        "The inventor of the Waffle Iron did not like waffles.",
        "George W. Bush was once a cheerleader.",
        "In Japan, it is completely acceptable to name your child ‘Buttocks’ or ‘Prostitute’",
        "In 1895 Hampshire police handed out the first ever speeding ticket, fining a man for doing 6mph!",
        "Each year, there are more than 40,000 toilet related injuries in the United States.",
        "A tapir has the largest penis-to-body ratio of any animal.",
        "Mewtwo is a clone of the Pokémon Mew, yet it comes before Mew in the Pokédex.",
        "Every year more than 2500 left-handed people are killed from using right-handed products.",
        "Madonna suffers from garophobia which is the fear of thunder.",
        "China has more English speakers than the United States.",
        "Samuel L. Jackson requested to have a purple light saber in Star Wars in order for him to accept the part as Mace Windu.",
        "Paraskavedekatriaphobia is the fear of Friday the 13th!",
        "Kleenex tissues were originally used as filters in gas masks.",
        "In 1998, Sony accidentally sold 700,000 camcorders that had the technology to see through people’s clothes. These cameras had special lenses that use infrared light, which allowed you to see through some types of clothing.",
        "Ronald McDonald is “Donald McDonald” in Japan because it makes pronunciation easier for the Japanese. In Singapore he’s known as “Uncle McDonald”.",
        "The average raindrop falls at 7 miles per hour.",
        "Rats and horses can’t vomit.",
        "Netherlands is the only country with a national dog.",
        "Ancient Egyptian priests would pluck every hair from their bodies.",
        "About seven million cars are junked each year in the U.S.",
        "A rodents teeth never stop growing. They are worn down by the animal’s constant gnawing on bark, leaves, and other vegetables.",
        "Camel’s milk does not curdle.",
        "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first class.",
        "In 1933, Mickey Mouse, an animated cartoon character, received 800,000 fan letters.",
        "Flies jump backwards during takeoff.",
        "Benjamin Franklin was the fifth in a series of the youngest son of the youngest son.",
        "Human thigh bones are stronger than concrete.",
        "The people of Israel consume more turkeys per capita than any other country.",
        "In Quebec, there is an old law that states margarine must be a different color than butter.",
        "A “quidnunc” is a person who is eager to know the latest news and gossip.",
        "It’s possible to lead a cow upstairs…but not downstairs.",
        "Human thighbones are stronger than concrete.",
        "A group of hares is called a Husk.",
        "There are more than 10 million bricks in the Empire State Building.",
        "Dreamt is the only English word that ends in the letters “MT”.",
        "In New York State, it is illegal to but any alcohol on Sundays before noon.",
        "98% of Japanese are cremated.",
        "For every ‘normal’ webpage, there are five porn pages.",
        "Arnold Schonberg suffered from triskaidecphobia, the fear of the number 13. He died 13 minutes from midnight on Friday the 13th.",
        "Montpelier, Vermont is the only state capital without a McDonalds.",
        "A cow gives nearly 200,000 glasses of milk in her lifetime.",
        "Cuba is the only island in the Caribbean to have a railroad.",
        "Earthworms have 5 hearts.",
        "People say “bless you” when you sneeze because your heart stops for a millisecond."
        
    ]
    
    func getRandomFact() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextIntWithUpperBound(facts.count)
        return facts[randomNumber]
    }
    
}
